---
- hosts: localhost

    - include: install_ubuntu.yml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - include: install_centos.yml
      when: ansible_distribution == 'CentOS' 

    - name: 'Installing Ansible dependencies'
      easy_install:
        name: pip

    - name: 'Installing PIP dependencies'
      pip:
        name: "{{ item.name | default(item) }}"
        state: present
        version: "{{ item.version | default(omit) }}"
      with_items: 
        - docker-py

    - name: Installing packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - python-setuptools

    - name: Installing docker compose
      pip:
        name: docker-compose
        version: "{{ docker_compose_version | default('1.22.0') }}"
        state: present